services:
  - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test

build-backend:
  stage: test
  image: docker:24.0.5
  script:
    - docker build -t meditrack-backend backend/

build-frontend:
  stage: test
  image: docker:24.0.5
  script:
    - docker build -t meditrack-frontend frontend/

test-backend:
  stage: test
  image: maven:3-openjdk-17
  script:
    - cd backend
    - mvn verify
