image: maven:3-openjdk-17

variables:
  GIT_STRATEGY: "clone"

stages:
  - test
  - build

test-backend:
  stage: test
  script:
    - cd backend
    - mvn clean test

test-frontend:
  stage: test
  image: node:lts
  script:
    - cd frontend
    - npm install
    - npm run test

backend_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd backend
    - docker build -t backend-image .

frontend_build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd frontend
    - docker build -t frontend-image .
