image: maven:3-openjdk-17

variables:
  GIT_STRATEGY: "clone"
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay

services:
  - docker:18.09.7-dind

stages:
  - test
  - build
  - deploy

test-backend:
  stage: test
  script:
    - cd backend
    - mvn clean install

test-frontend:
  stage: test
  image: node:lts
  script:
    - cd frontend
    - npm run lint
    - npm run build

backend_build:
  stage: build
  image: docker:18.09.7-dind
  script:
    - cd backend
    - docker build -t backend-image .

frontend_build:
  stage: build
  image: docker:18.09.7-dind
  script:
    - cd frontend
    - docker build -t frontend-image .

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d