image: maven:3-openjdk-17

variables:
  GIT_STRATEGY: "clone"

services:
    - docker:dind

stages:
  - build
  - deploy

backend_build:
  stage: build
  image: docker:latest
  script:
    - cd backend
    - docker build -t backend-image .

frontend_build:
  stage: build
  image: docker:latest
  script:
    - cd frontend
    - docker build -t frontend-image .

deploy:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml up -d