image: maven:3-openjdk-17

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:19.03.12-dind

stages:
  - build
  - test

build:
  image: docker/compose:1.29.2
  stage: build
  script:
    - echo "Building the project..."
    - docker-compose -f docker-compose.yml build -e POSTGRES_USER=meditrack -e POSTGRES_DB=meditrack

build-backend:
  image: docker/compose:1.29.2
  stage: build
  script:
    - echo "Building the backend..."
    - docker-compose -f docker-compose.yml build -e POSTGRES_USER=meditrack -e POSTGRES_DB=meditrack backend

test:
  image: docker/compose:1.29.2
  stage: test
  script:
    - echo "Running tests..."
    - docker-compose -f docker-compose.yml run --rm backend mvn test