# This is a basic GitLab CI/CD configuration file.

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the project..."

test:
  stage: test
  script:
    - echo "Running tests..."