version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=meditrack
      - POSTGRES_USER=meditrack
      - POSTGRES_PASSWORD=PFtkqhXnCxFSScMY5Zh5
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://postgres:5432/meditrack
      - POSTGRES_USER=meditrack
      - POSTGRES_PASSWORD=PFtkqhXnCxFSScMY5Zh5
    depends_on:
      postgres:
        condition: service_healthy

  angular:
    profiles:
      - never # TODO: remove this when frontend is ready
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"